#!/usr/bin/env bash
#Redirects to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '/listen 80 default_server;/ a \\trewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service restart
