#!/usr/bin/env bash
# configures a brand new Ubuntu machine
sudo apt -y update
sudo apt -y install nginx
sudo sed -i '/listen 80 default_server;/ a \\t add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
