#!/usr/bin/env bash
#Install load balancer
sudo apt -y update
sudo apt -y install haproxy

echo "
frontend web-fronted
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    mode http
    balance roundrobin
    server 155384-web-01 18.206.202.177 check
    server 155384-web-02 100.25.31.46 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo chmod +x /etc/init.d/haproxy
sudo service haproxy restart
