#!/usr/bin/env bash
# Script that sets port 80 
sudo apt -y update
sudo apt -y install nginx
sudo sed -i '/listen 80 default_server ipv4only=on;' /etc/nginx/sites-available default
sudo service nginx start
